version: '3'
services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
  php:
    build: ./php
    ports:
      - '89:80'
    volumes:
      - ./var:/var
    depends_on:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - 8181:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: pass
      PMA_ARBITRARY: 1﻿
volumes:
  db:


    
